# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import greet_pb2 as greet__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in greet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IMAPClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchEmails = channel.unary_unary(
                '/e_client.IMAPClientService/FetchEmails',
                request_serializer=greet__pb2.LimitsRequest.SerializeToString,
                response_deserializer=greet__pb2.FetchEmailsResponse.FromString,
                _registered_method=True)
        self.FetchEmailInfo = channel.unary_unary(
                '/e_client.IMAPClientService/FetchEmailInfo',
                request_serializer=greet__pb2.IdEmailRequest.SerializeToString,
                response_deserializer=greet__pb2.FetchEmailInfoResponse.FromString,
                _registered_method=True)


class IMAPClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchEmails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchEmailInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IMAPClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchEmails': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchEmails,
                    request_deserializer=greet__pb2.LimitsRequest.FromString,
                    response_serializer=greet__pb2.FetchEmailsResponse.SerializeToString,
            ),
            'FetchEmailInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchEmailInfo,
                    request_deserializer=greet__pb2.IdEmailRequest.FromString,
                    response_serializer=greet__pb2.FetchEmailInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'e_client.IMAPClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('e_client.IMAPClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IMAPClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchEmails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e_client.IMAPClientService/FetchEmails',
            greet__pb2.LimitsRequest.SerializeToString,
            greet__pb2.FetchEmailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchEmailInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/e_client.IMAPClientService/FetchEmailInfo',
            greet__pb2.IdEmailRequest.SerializeToString,
            greet__pb2.FetchEmailInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
