# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greet.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'greet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x08\x65_client\".\n\rLimitsRequest\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"\x1c\n\x0eIdEmailRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"Q\n\x14SummaryEmailResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\"I\n\x13\x46\x65tchEmailsResponse\x12\x32\n\nemailsList\x18\x01 \x03(\x0b\x32\x1e.e_client.SummaryEmailResponse\"v\n\x16\x46\x65tchEmailInfoResponse\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x0c\n\x04\x62ody\x18\x05 \x01(\t\x12\x13\n\x0b\x61ttachments\x18\x06 \x03(\t2\xa8\x01\n\x11IMAPClientService\x12\x45\n\x0b\x46\x65tchEmails\x12\x17.e_client.LimitsRequest\x1a\x1d.e_client.FetchEmailsResponse\x12L\n\x0e\x46\x65tchEmailInfo\x12\x18.e_client.IdEmailRequest\x1a .e_client.FetchEmailInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIMITSREQUEST']._serialized_start=25
  _globals['_LIMITSREQUEST']._serialized_end=71
  _globals['_IDEMAILREQUEST']._serialized_start=73
  _globals['_IDEMAILREQUEST']._serialized_end=101
  _globals['_SUMMARYEMAILRESPONSE']._serialized_start=103
  _globals['_SUMMARYEMAILRESPONSE']._serialized_end=184
  _globals['_FETCHEMAILSRESPONSE']._serialized_start=186
  _globals['_FETCHEMAILSRESPONSE']._serialized_end=259
  _globals['_FETCHEMAILINFORESPONSE']._serialized_start=261
  _globals['_FETCHEMAILINFORESPONSE']._serialized_end=379
  _globals['_IMAPCLIENTSERVICE']._serialized_start=382
  _globals['_IMAPCLIENTSERVICE']._serialized_end=550
# @@protoc_insertion_point(module_scope)
